### ISSUE TITLE
Ausführen von Makros

### ISSUE THREAD

**Issue by Laurenz1606** [powercode-boys/digital-macro-pad#26]
Ich als Makropoweruser möchte auf Klick des Playbuttons ein Makro ausführen können.

- [x] beim Klick auf den Playbutton wird der hinterlegte Befehl ausgeführt
- [x] das Terminal öffnet sich beim Ausführen des Befehls nicht

**Comment by Ediz97** [comment]
- Wie lässt sich mit Electron ein Befehl ausführen? (https://stackoverflow.com/questions/50507531/is-there-a-way-to-launch-a-terminal-window-or-cmd-on-windows-and-pass-run-a-co)
- Befehl an das Backend senden und ausführen
