### ISSUE TITLE
Suche nach allen Kategorien (Titel, Beschreibung, Befehl)

### ISSUE THREAD

**Issue by Laurenz1606** [powercode-boys/digital-macro-pad#28]

**Comment by MrShipooopi** [comment]
Ich als Makropoweruser möchte nach allen Feldern in meinen Makros suchen können, um z.B. auch alle "git"-Makros schnell finden zu können (Suche nach Befehl)

- [x] Bei Eingabe in das Suchfeld wird die Beschreibung der Makros durchsucht
- [x] Bei Eingabe in das Suchfeld wird der Befehl der Makros durchsucht
- [x] Bei Eingabe in das Suchfeld wird weiterhin der Titel der Makros durchsucht
- [x] Solange das Suchfeld gefüllt ist, werden nur die gefilterten Makros angezeigt
- [x] Ist das Suchfeld leer, werden alle Makros angezeigt
