### ISSUE TITLE
Kopieren in die Zwischenablage

### ISSUE THREAD

**Issue by Laurenz1606** [powercode-boys/digital-macro-pad#5]
Ich als Makropoweruser möchte meine Makros auch nutzen können und entsprechend den Befehl eines Makros mir in die Zwischenablage kopieren.

- [x] Makro-Befehl kann in die Zwischenablage kopiert werden ohne "Strg + C" zu verwenden

**Comment by MrShipooopi** [comment]
Fahrplan:

- Button für Copy hinzufügen
- Button optimalerweise generisch
- Tooltip auf Button**klick** für X Sekunden anzeigen
- In Svelte mit Boolean und If-Block togglen
