### ISSUE TITLE
Makro speichern

### ISSUE THREAD

**Issue by Laurenz1606** [powercode-boys/digital-macro-pad#9]
Ich als Makropoweruser möchte, dass meine Makros nach dem Schließen und erneutem Öffnen der App noch vorhanden sind, um nicht alles immer neu eintragen zu müssen.

- [x] Makros werden gespeichert
- [x] Bei einem Neustart der App sind alle Makros noch so vorhanden, wie vor dem Schließen

**Comment by Laurenz1606** [comment]
https://stackoverflow.com/questions/19275776/node-js-how-to-get-the-os-platforms-user-data-folder

**Comment by MrShipooopi** [comment]
Fahrplan:

- Task: Wie kommt man in den App_data-Ordner des Nutzers / Wo wird die Json gespeichert?
- Task: Im Backend Beispiel-Json-Datei erzeugen und speichern
- Task: Beim Starten der App Json-Datei einlesen (falls vorhanden) (siehe https://stackoverflow.com/questions/63380478/where-do-i-execute-my-on-first-start-functions-in-my-electron-app)
- Task: Frontend-Backend-Kommunikation alle Makros rübersenden (Im Svelte-Store subscriben und bei Änderung Speichern auslösen)
